# Numpy Exercise Solutions

Create a null vector of size 10

In [2]:
import numpy as np
Z = np.zeros(10)
print(Z)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Create a null vector of size 10 but the fifth value which is 1

In [3]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Create a vector with values ranging from 10 to 49

In [4]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Reverse a vector (first element becomes last)

In [5]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


How to convert  array into an integer (32 bits) in place a float (32 bits)?

In [8]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


Create a 10x10 array with random values and find the minimum and maximum values 

In [9]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0168614276114 0.992338875095


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [10]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)



[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


Subtract the mean of each row of a matrix

In [11]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[ 0.1976819   0.10529707  0.19494139  0.34036183 -0.03744546 -0.11001916
  -0.47385412  0.00246381 -0.33536471  0.11593746]
 [-0.13365359 -0.0403235   0.14955841  0.01180468  0.28308424 -0.45779406
  -0.20283137  0.1362067  -0.03160829  0.28555679]
 [-0.49804679 -0.2394419  -0.23207943  0.34835804  0.09593909 -0.12008392
   0.00255229 -0.02114355  0.43228864  0.23165753]
 [-0.06783093 -0.09880351  0.41699003  0.09622746 -0.29753913 -0.26129078
   0.15350867 -0.23740444  0.33896415 -0.04282152]
 [-0.10462363  0.3533838  -0.19212405 -0.09520669  0.30365058  0.20685771
  -0.30523996 -0.44507541  0.13035025  0.1480274 ]]


More Exercises: https://github.com/rougier/numpy-100/blob/master/100%20Numpy%20exercises.md